//
//  PizzeriasListModels.swift
//  Pizzarello
//
//  Created by Oleksandr Nechet on 23.07.17.
//  Copyright (c) 2017 Oleksandr Nechet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PizzeriasList
{
    // MARK: Use cases
    
    enum FetchPizzerias
    {
        struct Request
        {
        }
        struct Response
        {
            var result: PizzeriasResponse<[Pizzeria]>
        }
        struct ViewModel
        {
            struct DisplayedPizzerias
            {
                var id: String
                var name: String
                var distance: String
            }
            var displayedPizzerias: [DisplayedPizzerias]
        }
    }
}
