//
//  PizzeriasListRouter.swift
//  Pizzarello
//
//  Created by Oleksandr Nechet on 23.07.17.
//  Copyright (c) 2017 Oleksandr Nechet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PizzeriasListRoutingLogic
{
    func routeToShowPizzeriaDetails(segue: UIStoryboardSegue)
}

class PizzeriasListRouter: NSObject, PizzeriasListRoutingLogic
{
    weak var viewController: PizzeriasListViewController?
    var dataStore: PizzeriasListDataStore?
    
    //MARK: - PizzeriasListRoutingLogic
    
    func routeToShowPizzeriaDetails(segue: UIStoryboardSegue)
    {
        let destinationVC = segue.destination as! PizzeriaDetailsViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToPizzeriaDetails(source: dataStore!, destination: &destinationDS)
    }
    
    //MARK: - Passing data
    
    func passDataToPizzeriaDetails(source: PizzeriasListDataStore, destination: inout PizzeriaDetailsDataStore)
    {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        destination.pizzeria = source.pizzerias[selectedRow!]
    }
}
