//
//  PizzeriaDetailsPresenter.swift
//  Pizzarello
//
//  Created by Oleksandr Nechet on 25.07.17.
//  Copyright (c) 2017 Oleksandr Nechet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PizzeriaDetailsPresentationLogic
{
    func presentPizzeria(_ pizzeria: Pizzeria)
}

class PizzeriaDetailsPresenter: PizzeriaDetailsPresentationLogic
{
    weak var viewController: PizzeriaDetailsDisplayLogic?
    
    //MARK: - PizzeriaDetailsPresentationLogic
    
    func presentPizzeria(_ pizzeria: Pizzeria)
    {
        let presentedPizzeriaInfo = [PizzeriaDetails.ViewModel.DisplayedItem(title: "venue: ",
                                                                             value: pizzeria.name),
                                     PizzeriaDetails.ViewModel.DisplayedItem(title: "distance: ",
                                                                             value: String(pizzeria.distance))]
        
        let viewModel = PizzeriaDetails.ViewModel(displayedItems: presentedPizzeriaInfo)
        
        viewController?.displayPizzeriaInfo(viewModel: viewModel)
    }
}
